[Enhancement] Add option to use existing Media Profile as template for new profile
kieraneglin/pinchflat pull request #466
Opened 2024-11-09 22:39 UTC by loop-index

## What's new?

Replicated the "Use as Template" feature from Sources to Media Profiles. Existing profile can now be used as a template to create new profiles as requested in #459. Option can be found under the Actions dropdown in the Media Profile view.

## What's changed?

N/A

## What's fixed?

N/A

## Any other comments?

There was some weird behavior: It seems like having parameters in the new Profile form fires a PUT request instead of a POST request like it should. To fix that I basically replicated what was done on the Source form and specified explicit methods. All tests are now passing.

- [x] I am the original author of this code and I am giving it freely to the community and Pinchflat project maintainers

2024-11-12 19:02 UTC, kieraneglin requested changes
Overall this looks good! Thank you for the contribution 💪 

I left one small comment, and I'd also love it if you could add a test for this to `media_profile_controller_test.exs`. You can see an example test in `test/pinchflat_web/controllers/source_controller_test.exs` on line 74

2024-11-13 18:19 UTC, loop-index commented
Thanks for the review! I added in another commit for the Source deletion, but my local build is acting up so I'm trying to resolve it before I can validate the new test.

2024-11-13 21:25 UTC, kieraneglin commented
Thanks! Let me know if there's anything I can help with re: local build. Are you running the build through a Docker container?

2024-11-14 23:51 UTC, kieraneglin commented
I'm going on a trip from tomorrow through to Tuesday, but if you're still having troubles with your local env by the time I'm back I could go in and add that test if you'd like 🤙

2024-11-19 19:09 UTC, loop-index commented
Sorry for the delay, I was busy the past few days. I was able to run the application with a dev container and write the test. I'm basing it off the corresponding test for Source, but since the Profile schema consists mostly of Enums which was hard to test with the HTTP response, the test might be a bit lackluster.

2024-11-20 17:56 UTC, kieraneglin commented
Thank you! It's almost over the finish line - would you mind running `mix check` locally to address the outstanding CI issues? `mix check` alone should actually fix the issues so you just need to commit them

2024-11-20 18:06 UTC, loop-index commented
Ran and committed! Let me know if there are any other issues.

2024-11-20 18:25 UTC, merged

2024-11-20 18:25 UTC, kieraneglin commented
Looks good to me! Thank you for taking care of that 🎉

2024-11-20 18:27 UTC, loop-index commented
This was a great learning experience, thank you for pointing me in the right direction!